### ISSUE TITLE
Please update the docs to include the unit used for measuring distance... feet, yard, meter, mile

### ISSUE THREAD

**Issue by jonathanhollander** [myflashlab/GPS-ANE#1]
I just recently purchased this ANE and it works great but the authors left out 1 Crucial bit of information.

There are 3 different methods within the ANE that refer to distance but they give you no idea what the units used for the measurement are... Is this is Feet, Meters, yards, Miles, KM or What?

Gps.location.start(LocationAccuracy.HIGH, IS_THIS_NUMBER_FEET_MILES_YARDS_KM_OR_WHAT?, 10000);

var someNumberInFeet_Miles_Yards_KM_OR_SOMETHING:Number = GpsTools.bearing();
var someNumberInFeet_Miles_Yards_KM_YOU_DECIDE_AND_HOPE_YOUR_RIGHT:Number = GpsTools.distance();

**Comment by jonathanhollander** [comment]
I also have the demo version working within my app. I recently bought the commercial version and replaced the demo with it. I am now unable to compile the app. I get this error while trying to compile.

Error occurred while packaging the application:


dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:

java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;

	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)

	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)

	at com.android.dx.command.dexer.Main.processClass(Main.java:737)

	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)

	at com.android.dx.command.dexer.Main.access$300(Main.java:83)

	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)

	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)

	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)

	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)

	at com.android.dx.command.dexer.Main.processOne(Main.java:637)

	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)

	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)

	at com.android.dx.command.dexer.Main.run(Main.java:247)

	at com.android.dx.command.dexer.Main.main(Main.java:215)

	at com.android.dx.command.Main.main(Main.java:106)

1 error; aborting

**Comment by myflashlab** [comment]
Sorry for the late reply. we are busily moving myappsnippet to a new server and upgrading the whole thing which should be finished soon.

anyway, about your first question, 
> s this is Feet, Meters, yards, Miles, KM or What?

you're right, we missed that in the asdoc. we'll make sure the asdoc will be fixed soon. but dor now, you're good to know that the unit is "meters"

-------------------------------------------
about this problem: ```java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;```

make sure the following is checked:
* you are using Air SDK 18 or higher
* you are compiling on captive mode
* Are you sure you are not using both extensions? the demo and the purchased one? because only one of them must be active in your project. the same goes with the dependency ane file. you should have only one of the dependency ane files in your project.

if all above are checked, it is possible that you are using another .ane from another company which is conflicting with ours. disable them and see if you can compile fine now?

**Comment by jonathanhollander** [comment]
I am still getting the same error. 

I am using AIR SDK 19.
I am using captive mode.
I am 1000% sure I'm using the purchased one as the demo version works correctly and will compile. Only when I switch the demo for the purchased version am I getting this compile error.

I am ONLY using this 1 ANE... I also am including the "commonDependenciesV4.0.ane" as it was required to compile the demo as well.

**Comment by myflashlab** [comment]
OH MY GOD. That was a mistake on our side. while the php team was moving the files to the new myappsnippet server, they had somehow uploaded a wrong version. please try downloading the ANE from your panel once again and it should be fine now. I just tested it myself. if you have problem downloading the correct V2.0 please drop us an email from the contact form on the home page pf myappsnippet.com sorry for the inconvenient.
