### ISSUE TITLE
Cannot compile in Android - dependencies errors?

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [myflashlab/GPS-ANE#12]
I downloaded the GPS ANE and the dependencies, I put them in my project along with some test code but when I try to compile I get a window with about 7 error messages that I think that have to do with some conflicts in the dependencies. Some of them are like: 
"google-play-services-res\values\common_attrs.xml:13: error: Attribute imageAspectRatioAdjust has already been defined",
"google-play-services-res\values\common_attrs.xml:22: error: Attribute imageAspectRatio has already been defined",
"google-play-services-res\values\common_attrs.xml:27: error: Attribute circleCrophas already been defined",
"com.google.android.gms.location-res\layout-v21\place_autocomplete_fragment.xml:11: error:Error: No resource found that matches the given name (at background with value ?android:selectableAttributeBackgroundBorderless)
...and some more like that.

The thing is that we use a lot of other ANEs in the app (inAppBilling, Camera, DeviceMorion, Application from distriqt, pushWoosh ANE and a couple of others). Is it possible that there are conflicts between them and, if this is the case, how can we overpass them?

**Comment by myflashlab** [comment]
The error messages show conflicts between ANEs. That's a fact. I can give you an advice that you might find helpful but we cannot guarantee that because we have no idea how other ANE providers has built their ANEs!

#1) Try not including the dependencies from ours. and use the core GPS ANE only. If other ANE providers has build their ANEs professionally enough, their Google Play Services ANE must be using the latest version and be independent enough so the GPS ANE can work with it.

#2) If other ANEs have dependencies too, try not including them and instead use the dependencies from ours.

If none of the above solutions work, you need to try using ANEs from one developer only to make sure no conflicts would ever happen. checkout our club membership if you are interested: http://www.myflashlabs.com/product/myflashlabs-club-membership/

**Comment by myflashlab** [comment]
Please update this ticket on how it went. If you have a question, please do ask.

**Comment by Nikos-Laskaridis** [comment]
Unfortunately I couldn't make it work by removing the dependencies. And it's a pity because it looks like a great ANE. If anything changes though I'm still interested.
Cheers
